### ISSUE TITLE
timedGate not working..but can be easily solved

### ISSUE THREAD

**Issue by ichingxs4all** [ianhattwick/modularCV#2]
The timedGate function was not working in the library, but if you change it to:

void controlVoltage::timedGate(int gateLen) {
  _outVal = (1<<_bitDepth) - 1;
  _gateLen = gateLen;
  _triggerTimer = millis();
  _state = 2;
}

it works

**Comment by ianhattwick** [comment]
Thanks for the fix - I just pushed it, let me know if you find anything else :-)

**Comment by ianhattwick** [comment]
Updated controlVoltage.cpp with code suggested by ichingfx4all
